### ISSUE TITLE
execute output file without pop-up console window

### ISSUE THREAD

**Issue by Hhhhelix** [frkngksl/Huan#5]
How to improve the code so that the output file can execute without pop-up window?

**Comment by Hhhhelix** [comment]
I added the following code to "loader.cpp", it works but the output PE file was killed by anti-virus software when executed, how to improve it ? 

"#pragma comment(linker, "/subsystem:\"windows\" /entry:\"mainCRTStartup\"")"

**Comment by frkngksl** [comment]
Hi, 

First you should find whether there is a signature (byte sequences) in the PE loader that results in detection. If it is, you can change this byte sequence to avoid detection (like a function name, section name etc.). If it is other than that, it might be a behavior based detection, so you may want to change the execution algorithm (adding sleeps, using different algorithms etc.)
