### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by m0rt1f3r** [frkngksl/Huan#6]
Hi @frkngksl 
I'm using Ubuntu and am new to Visual Studio. It seems that C++ projects cannot be built with Mono and Visual Studio is known to work poorly with Wine.
Could you please build the project and release it on your repo ?
Thank you.

**Comment by zeltrax00** [comment]
Did you try using VirtualBox ?

**Comment by frkngksl** [comment]
Hi @m0rt1f3r , as @zeltrax00 indicated, you can try Virtualbox, I'm not planning to create a release package.
