### ISSUE TITLE
relocation table

### ISSUE THREAD

**Issue by qeweqradasf1231** [frkngksl/Huan#7]
[+] Data is decrypted!
[!] No Relocation Table and Cannot load to the preferable address
how to fix it?

**Comment by frkngksl** [comment]
Your chosen payload should have a relocation table to fix RVA at runtime.

**Comment by qeweqradasf1231** [comment]
> Your chosen payload should have a relocation table to fix RVA at runtime.
how can i do this thing ?

**Comment by qeweqradasf1231** [comment]
> Your chosen payload should have a relocation table to fix RVA at runtime.

how can i do this thing ?
